version: '3.8'
services:
  postgres:
    container_name: postgres_student_service
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # postgres2:
  #   container_name: postgres_smartmore_identity
  #   image: postgres
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - ./data/postgres2:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  # authz-service:
  #   image: "authz-service-express"
  #   ports:
  #     - '8080:3000'
  #   environment:
  #     - PORT=3000
  #     - PUBLIC_PORT=8080
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   links:
  #     - postgres
  # authn-service:
  #   image: "authn-service"
  #   ports:
  #     - 8081:3000
  #   environment:
  #     - PORT=3000
  #     - PUBLIC_PORT=8081
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   links:
  #     - postgres
